# Generated by Django 6.0.5 on 2026-05-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("hashed_password", models.CharField(max_length=100)),
                ("points_per_second", models.IntegerField(default=0)),
                ("points_per_click", models.IntegerField(default=1)),
            ],
        ),
    ]
