# Generated by Django 6.0.5 on 2026-05-19 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("hashed_password", models.CharField(max_length=255)),
                ("points_per_second", models.IntegerField(default=0)),
                ("points_per_click", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "Uživatel",
                "verbose_name_plural": "Uživatelé",
            },
        ),
        migrations.CreateModel(
            name="UserUpgrade",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "upgrade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_upgrades",
                        to="game.upgrade",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_upgrades",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vylepšení",
                "verbose_name_plural": "Vylepšení",
                "unique_together": {("user", "upgrade")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="upgrades",
            field=models.ManyToManyField(
                related_name="users", through="users.UserUpgrade", to="game.upgrade"
            ),
        ),
    ]
