# Generated by Django 6.0.5 on 2026-05-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="hashed_password",
            field=models.CharField(max_length=255),
        ),
    ]
