# Generated by Django 6.0.5 on 2026-05-07 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_hashed_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserUpgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upgrade_name", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrades",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "upgrade_name")},
            },
        ),
    ]
