# Generated by Django 6.0.5 on 2026-05-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userupgrade"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Uživatel", "verbose_name_plural": "Uživatelé"},
        ),
        migrations.AlterModelOptions(
            name="userupgrade",
            options={"verbose_name": "Vylepšení", "verbose_name_plural": "Vylepšení"},
        ),
        migrations.AlterField(
            model_name="userupgrade",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
