# Generated by Django 6.0.5 on 2026-05-19 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("points", models.BigIntegerField(default=0)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Bodování",
                "verbose_name_plural": "Bodování",
            },
        ),
        migrations.CreateModel(
            name="Upgrade",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("cost", models.IntegerField()),
                ("pps", models.IntegerField()),
                ("ppc", models.IntegerField()),
            ],
        ),
    ]
