# Generated by Django 6.0.5 on 2026-05-07 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
        ("users", "0003_userupgrade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="points",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="score",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="score",
                to="users.user",
            ),
        ),
    ]
