# Generated by Django 6.0.5 on 2026-05-07 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_alter_score_points_alter_score_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="last_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
