# Generated by Django 6.0.5 on 2026-05-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_alter_score_last_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="score",
            options={"verbose_name": "Bodování", "verbose_name_plural": "Bodování"},
        ),
    ]
