# Generated by Django 6.0.5 on 2026-05-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_alter_score_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Upgrade",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("cost", models.IntegerField()),
                ("pps", models.IntegerField()),
                ("ppc", models.IntegerField()),
            ],
        ),
    ]
